/** asn1.h - header file for ASN1 */
#ifndef ASN1_H
#define ASN1_H

#define ASN1_TAG_MASK 0xdf /* Take out P/C flag */
#define ASN1_C_P_MASK 0x20
#define ASN1_IS_CONSTRUCTED(identifier) ((identifier) & ASN1_C_P_MASK)
#define ASN1_INDEFINITE_FORM 0x80
#define ASN1_INDEFINITE_LENGTH 0xffff

#define ASN_BOOLEAN_TRUE 0xff
#define ASN_BOOLEAN_FALSE 0x00

enum ASN1_TAG {
	ASN1_TAG_EOC = 0,
	ASN1_TAG_BOOLEAN = 1,
	ASN1_TAG_INTEGER = 2,
	ASN1_TAG_BIT_STRING = 3,
	ASN1_TAG_OCTET_STRING = 4,
	ASN1_TAG_NULL = 5,
	ASN1_TAG_OBJECT_IDENTIFIER = 6,
	ASN1_TAG_OBJECT_DESCRIPTOR = 7,
	ASN1_TAG_EXTERNAL = 8,
	ASN1_TAG_REAL = 9,
	ASN1_TAG_ENUMERATED = 10,
	ASN1_TAG_EMBEDDED_PDV = 11,
	ASN1_TAG_UTF8_STRING = 12,
	ASN1_TAG_RELATIVE_OID = 13,
	ASN1_TAG_TIME = 14,
	ASN1_TAG_RESERVED = 15,
	ASN1_TAG_SEQUENCE = 16,
	ASN1_TAG_SET = 17,
	ASN1_TAG_NUMERIC_STRING = 18,
	ASN1_TAG_PRINTABLE_STRING = 19,
	ASN1_TAG_T61_STRING = 20,
	ASN1_TAG_VID_STRING = 21,
	ASN1_TAG_IA5_STRING = 22,
	ASN1_TAG_UTC = 23,
	ASN1_TAG_GENERALIZED_TIME = 24,
	ASN1_TAG_GRAPHIC_STRING = 25,
	ASN1_TAG_VISIBLE_STRING = 26,
	ASN1_TAG_GENERAL_STRING = 27,
	ASN1_TAG_UNIVERSAL_STRING = 28,
	ASN1_TAG_CHARACTER_STRING = 29,
	ASN1_TAG_BMP_STRING = 30,
	ASN1_TAG_DATE = 31,
	ASN1_TAG_TIME_OF_DAY = 32,
	ASN1_TAG_DATE_TIME = 33,
	ASN1_TAG_DURATION = 34,
	ASN1_TAG_OID_IRI = 35,
	ASN1_TAG_RELATIVE_OID_IRI = 36,
	ASN1_TAG_CONTEXT_SPECIFIC_0 = 0x80,
	ASN1_TAG_CONTEXT_SPECIFIC_1 = 0x81,
	ASN1_TAG_CONTEXT_SPECIFIC_2 = 0x82,
	ASN1_TAG_CONTEXT_SPECIFIC_3 = 0x83,
	ASN1_TAG_CONTEXT_SPECIFIC_4 = 0x84,
	ASN1_TAG_CONTEXT_SPECIFIC_5 = 0x85,
	ASN1_TAG_CONTEXT_SPECIFIC_6 = 0x86,
	ASN1_TAG_CONTEXT_SPECIFIC_7 = 0x87,
	ASN1_TAG_CONTEXT_SPECIFIC_8 = 0x88,
	/* Add more tags here */
	ASN1_TAG_UNKNOWN = 0xff
};

#endif /* ASN1_H */